#!/usr/bin/env bun
/**
 * Seeds the spotle_artists table with an initial pool of well-known artists.
 * Run: bun run scripts/seed-spotle.ts
 *
 * Spotify IDs can be verified/updated using the Spotify Web API.
 * Fields: creationYear, memberCount, vocalType, primaryLanguage, instrumentation
 * are manually curated and not available from Spotify directly.
 */
import { db } from "../src/db";
import { games, spotleArtists } from "../src/db/schema";

const ARTISTS = [
  {
    id: "4tZwfgrHOc3mvqYlEYSvVi",
    name: "Daft Punk",
    creationYear: 1993,
    memberCount: 2,
    spotifyFollowers: 8400000,
    genres: ["french house", "electronic", "dance"],
    country: "FR",
    vocalType: "Mixed",
    primaryLanguage: "English",
    mostFamousSong: { title: "Get Lucky", spotifyStreams: 1200000000 },
    instrumentation: "Electronic",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "6vWDO969PvNqNYHIOW5v0m",
    name: "Beyoncé",
    creationYear: 2003,
    memberCount: 1,
    spotifyFollowers: 34000000,
    genres: ["pop", "r&b", "soul"],
    country: "US",
    vocalType: "Female",
    primaryLanguage: "English",
    mostFamousSong: { title: "Crazy in Love", spotifyStreams: 1100000000 },
    instrumentation: "Live",
    appearsOnSoundtracksWith: ["3nFkdlSjzX9mRTtwJOzDYB"], // Jay-Z
    imageUrl: null,
  },
  {
    id: "3WrFJ7ztbogyGnTHbHJFl2",
    name: "The Beatles",
    creationYear: 1960,
    memberCount: 4,
    spotifyFollowers: 27000000,
    genres: ["british invasion", "classic rock", "pop"],
    country: "GB",
    vocalType: "Mixed",
    primaryLanguage: "English",
    mostFamousSong: { title: "Come Together", spotifyStreams: 800000000 },
    instrumentation: "Live",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "4Z8W4fKeB5YxbusRsdQVPb",
    name: "Radiohead",
    creationYear: 1985,
    memberCount: 5,
    spotifyFollowers: 10000000,
    genres: ["alternative rock", "art rock", "electronic"],
    country: "GB",
    vocalType: "Male",
    primaryLanguage: "English",
    mostFamousSong: { title: "Creep", spotifyStreams: 1400000000 },
    instrumentation: "Mixed",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "4dpARuHxo51G3z768sgnrY",
    name: "Adele",
    creationYear: 2006,
    memberCount: 1,
    spotifyFollowers: 62000000,
    genres: ["pop", "soul", "british soul"],
    country: "GB",
    vocalType: "Female",
    primaryLanguage: "English",
    mostFamousSong: { title: "Hello", spotifyStreams: 2800000000 },
    instrumentation: "Live",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "2YZyLoL8N0Wb9xBt1NhZWg",
    name: "Kendrick Lamar",
    creationYear: 2004,
    memberCount: 1,
    spotifyFollowers: 28000000,
    genres: ["hip hop", "west coast rap", "conscious hip hop"],
    country: "US",
    vocalType: "Male",
    primaryLanguage: "English",
    mostFamousSong: { title: "HUMBLE.", spotifyStreams: 2000000000 },
    instrumentation: "Electronic",
    appearsOnSoundtracksWith: ["3AA28KZvwAUcZuOKwyblJQ"], // Gorillaz
    imageUrl: null,
  },
  {
    id: "7Ln80lUS6He07XvHI8qqHH",
    name: "Arctic Monkeys",
    creationYear: 2002,
    memberCount: 4,
    spotifyFollowers: 21000000,
    genres: ["alternative rock", "indie rock", "sheffield indie"],
    country: "GB",
    vocalType: "Male",
    primaryLanguage: "English",
    mostFamousSong: { title: "Do I Wanna Know?", spotifyStreams: 1700000000 },
    instrumentation: "Live",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "06HL4z0CvFAxyc27GXpf02",
    name: "Taylor Swift",
    creationYear: 2004,
    memberCount: 1,
    spotifyFollowers: 100000000,
    genres: ["pop", "country pop", "singer-songwriter"],
    country: "US",
    vocalType: "Female",
    primaryLanguage: "English",
    mostFamousSong: { title: "Anti-Hero", spotifyStreams: 2400000000 },
    instrumentation: "Mixed",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "5pKCCKE2ajJHZ9KAiaK11H",
    name: "Rihanna",
    creationYear: 2003,
    memberCount: 1,
    spotifyFollowers: 57000000,
    genres: ["pop", "r&b", "dancehall"],
    country: "BB",
    vocalType: "Female",
    primaryLanguage: "English",
    mostFamousSong: { title: "Umbrella", spotifyStreams: 1500000000 },
    instrumentation: "Electronic",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "4gzpq5DuYFf6FTbr7dOWmV",
    name: "Coldplay",
    creationYear: 1996,
    memberCount: 4,
    spotifyFollowers: 75000000,
    genres: ["pop", "alternative rock", "post-britpop"],
    country: "GB",
    vocalType: "Male",
    primaryLanguage: "English",
    mostFamousSong: { title: "The Scientist", spotifyStreams: 1200000000 },
    instrumentation: "Live",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "6qqNVTkY8uBg9cP3Jd7DAH",
    name: "Billie Eilish",
    creationYear: 2015,
    memberCount: 1,
    spotifyFollowers: 80000000,
    genres: ["pop", "electropop", "dark pop"],
    country: "US",
    vocalType: "Female",
    primaryLanguage: "English",
    mostFamousSong: { title: "bad guy", spotifyStreams: 3200000000 },
    instrumentation: "Electronic",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "3AA28KZvwAUcZuOKwyblJQ",
    name: "Gorillaz",
    creationYear: 1998,
    memberCount: 4,
    spotifyFollowers: 14000000,
    genres: ["alternative hip hop", "virtual band", "trip hop"],
    country: "GB",
    vocalType: "Mixed",
    primaryLanguage: "English",
    mostFamousSong: { title: "Feel Good Inc.", spotifyStreams: 1000000000 },
    instrumentation: "Mixed",
    appearsOnSoundtracksWith: ["2YZyLoL8N0Wb9xBt1NhZWg"], // Kendrick
    imageUrl: null,
  },
  {
    id: "6tbjWDEIzxoDsBA1FuhndV",
    name: "Madonna",
    creationYear: 1982,
    memberCount: 1,
    spotifyFollowers: 18000000,
    genres: ["pop", "dance pop", "new wave"],
    country: "US",
    vocalType: "Female",
    primaryLanguage: "English",
    mostFamousSong: { title: "Like a Prayer", spotifyStreams: 900000000 },
    instrumentation: "Electronic",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "3YCKuqpv9nM9yMRNNEaWGH",
    name: "Stromae",
    creationYear: 2009,
    memberCount: 1,
    spotifyFollowers: 7000000,
    genres: ["electronic", "dance pop", "hip hop"],
    country: "BE",
    vocalType: "Male",
    primaryLanguage: "French",
    mostFamousSong: { title: "Papaoutai", spotifyStreams: 1100000000 },
    instrumentation: "Electronic",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "3kjuyTCjPG1Wjnwi974vOF",
    name: "Arcade Fire",
    creationYear: 2001,
    memberCount: 7,
    spotifyFollowers: 5000000,
    genres: ["indie rock", "art rock", "baroque pop"],
    country: "CA",
    vocalType: "Mixed",
    primaryLanguage: "English",
    mostFamousSong: { title: "Wake Up", spotifyStreams: 300000000 },
    instrumentation: "Mixed",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "3nFkdlSjzX9mRTtwJOzDYB",
    name: "Jay-Z",
    creationYear: 1986,
    memberCount: 1,
    spotifyFollowers: 13000000,
    genres: ["hip hop", "east coast hip hop", "gangsta rap"],
    country: "US",
    vocalType: "Male",
    primaryLanguage: "English",
    mostFamousSong: { title: "Empire State of Mind", spotifyStreams: 700000000 },
    instrumentation: "Electronic",
    appearsOnSoundtracksWith: ["6vWDO969PvNqNYHIOW5v0m"], // Beyoncé
    imageUrl: null,
  },
  {
    id: "7w29UYBi0qsHi5RTcv3lmA",
    name: "Björk",
    creationYear: 1977,
    memberCount: 1,
    spotifyFollowers: 5000000,
    genres: ["art pop", "avant-garde", "experimental"],
    country: "IS",
    vocalType: "Female",
    primaryLanguage: "English",
    mostFamousSong: { title: "Human Behaviour", spotifyStreams: 200000000 },
    instrumentation: "Electronic",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "2RdwBSPQiwcmiDo9kixcl8",
    name: "Pharrell Williams",
    creationYear: 1992,
    memberCount: 1,
    spotifyFollowers: 19000000,
    genres: ["pop", "hip hop", "neo soul"],
    country: "US",
    vocalType: "Male",
    primaryLanguage: "English",
    mostFamousSong: { title: "Happy", spotifyStreams: 2600000000 },
    instrumentation: "Electronic",
    appearsOnSoundtracksWith: ["4tZwfgrHOc3mvqYlEYSvVi"], // Daft Punk
    imageUrl: null,
  },
  {
    id: "0n2vTTFvRVDzAlcVefm2Yf",
    name: "Christine and the Queens",
    creationYear: 2010,
    memberCount: 1,
    spotifyFollowers: 2000000,
    genres: ["french indie pop", "synth-pop", "electropop"],
    country: "FR",
    vocalType: "Female",
    primaryLanguage: "French",
    mostFamousSong: { title: "Tilted", spotifyStreams: 250000000 },
    instrumentation: "Electronic",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "3YQKmKGau1PzlVlkL1iAx7",
    name: "Twenty One Pilots",
    creationYear: 2009,
    memberCount: 2,
    spotifyFollowers: 22000000,
    genres: ["alternative hip hop", "indie pop", "electropop"],
    country: "US",
    vocalType: "Male",
    primaryLanguage: "English",
    mostFamousSong: { title: "Stressed Out", spotifyStreams: 2000000000 },
    instrumentation: "Mixed",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "1HY2Jd0NmPuamShAr6KMms",
    name: "Lady Gaga",
    creationYear: 2006,
    memberCount: 1,
    spotifyFollowers: 50000000,
    genres: ["pop", "dance pop", "electropop"],
    country: "US",
    vocalType: "Female",
    primaryLanguage: "English",
    mostFamousSong: { title: "Bad Romance", spotifyStreams: 2200000000 },
    instrumentation: "Electronic",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "0k17h0D3J5VfsdmQ1iZtE9",
    name: "Pink Floyd",
    creationYear: 1965,
    memberCount: 4,
    spotifyFollowers: 23000000,
    genres: ["progressive rock", "psychedelic rock", "art rock"],
    country: "GB",
    vocalType: "Male",
    primaryLanguage: "English",
    mostFamousSong: { title: "Wish You Were Here", spotifyStreams: 900000000 },
    instrumentation: "Live",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "6FBDaR13swtiWwGhX1WQsP",
    name: "Nirvana",
    creationYear: 1987,
    memberCount: 3,
    spotifyFollowers: 19000000,
    genres: ["grunge", "alternative rock", "rock"],
    country: "US",
    vocalType: "Male",
    primaryLanguage: "English",
    mostFamousSong: { title: "Smells Like Teen Spirit", spotifyStreams: 1600000000 },
    instrumentation: "Live",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "3TVXtAsR1Inumwj472S9r4",
    name: "Drake",
    creationYear: 2006,
    memberCount: 1,
    spotifyFollowers: 85000000,
    genres: ["hip hop", "rap", "r&b"],
    country: "CA",
    vocalType: "Male",
    primaryLanguage: "English",
    mostFamousSong: { title: "God's Plan", spotifyStreams: 2300000000 },
    instrumentation: "Electronic",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "1Xyo4u8uXC1ZmMpatF05PJ",
    name: "The Weeknd",
    creationYear: 2009,
    memberCount: 1,
    spotifyFollowers: 90000000,
    genres: ["pop", "r&b", "dark r&b"],
    country: "CA",
    vocalType: "Male",
    primaryLanguage: "English",
    mostFamousSong: { title: "Blinding Lights", spotifyStreams: 4300000000 },
    instrumentation: "Electronic",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "66CXWjxzNUsdJxJ2JdwvnR",
    name: "Ariana Grande",
    creationYear: 2008,
    memberCount: 1,
    spotifyFollowers: 85000000,
    genres: ["pop", "dance pop", "r&b"],
    country: "US",
    vocalType: "Female",
    primaryLanguage: "English",
    mostFamousSong: { title: "Thank U, Next", spotifyStreams: 2100000000 },
    instrumentation: "Electronic",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "6l3HvQ5sa6mXTsMTB19rO5",
    name: "J. Cole",
    creationYear: 2007,
    memberCount: 1,
    spotifyFollowers: 22000000,
    genres: ["hip hop", "conscious hip hop", "east coast hip hop"],
    country: "US",
    vocalType: "Male",
    primaryLanguage: "English",
    mostFamousSong: { title: "No Role Modelz", spotifyStreams: 1800000000 },
    instrumentation: "Electronic",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "7dGJo4pcD2V6oG8kP0tJRR",
    name: "Eminem",
    creationYear: 1988,
    memberCount: 1,
    spotifyFollowers: 55000000,
    genres: ["hip hop", "rap", "detroit hip hop"],
    country: "US",
    vocalType: "Male",
    primaryLanguage: "English",
    mostFamousSong: { title: "Lose Yourself", spotifyStreams: 1700000000 },
    instrumentation: "Electronic",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "53XhwfbYqKCa1cC15pYq2q",
    name: "Imagine Dragons",
    creationYear: 2008,
    memberCount: 4,
    spotifyFollowers: 48000000,
    genres: ["pop rock", "indie pop", "alternative rock"],
    country: "US",
    vocalType: "Male",
    primaryLanguage: "English",
    mostFamousSong: { title: "Demons", spotifyStreams: 2700000000 },
    instrumentation: "Mixed",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
  {
    id: "4kI8Ie27vjR92waviDLUCf",
    name: "Camille",
    creationYear: 2002,
    memberCount: 1,
    spotifyFollowers: 600000,
    genres: ["french pop", "indie pop", "chanson"],
    country: "FR",
    vocalType: "Female",
    primaryLanguage: "French",
    mostFamousSong: { title: "Ta douleur", spotifyStreams: 60000000 },
    instrumentation: "Acoustic",
    appearsOnSoundtracksWith: [],
    imageUrl: null,
  },
];

await db.insert(games).values({ slug: "spotle", name: "Spotle" }).onConflictDoNothing();

for (const artist of ARTISTS) {
  await db
    .insert(spotleArtists)
    .values(artist)
    .onConflictDoUpdate({
      target: spotleArtists.id,
      set: { ...artist, updatedAt: new Date() },
    });
  console.log(`Seeded: ${artist.name}`);
}

console.log(`\nSeeded ${ARTISTS.length} artists into spotle_artists.`);
console.log("Run `bun run scripts/seed-spotle.ts` again to update.");
process.exit(0);
