#!/usr/bin/env python3
"""
Populate `originRegion` for all politicians using Wikidata P19 (place of birth).

  - Born in France   → French region name (e.g. "Hauts-de-France")
  - Born abroad      → Country name in French (e.g. "Algérie")
  - Not resolvable   → null

Uses cached QIDs from /tmp/qid_cache.json (generated by fetch_partis_full.py).

Phases:
  1. Batch-fetch P19 per politician QID          → /tmp/p19_cache.json
  2. Batch-fetch commune labels + P131 + P17     → /tmp/commune_cache.json
  3. Batch-fetch admin parents labels + P31      → /tmp/admin_cache.json
     + country labels for non-France births
  4. Resolve region / country, write politics.json
"""

import json, time, urllib.request, urllib.parse, sys, os

sys.stdout.reconfigure(line_buffering=True)

WD_ACTION   = "https://www.wikidata.org/w/api.php"
POLITICS    = "MikizBack/src/data/politics.json"
QID_CACHE   = "/tmp/qid_cache.json"
P19_CACHE   = "/tmp/p19_cache.json"
COMMUNE_CACHE = "/tmp/commune_cache.json"
ADMIN_CACHE = "/tmp/admin_cache.json"
BATCH       = 50
FRANCE_QID  = "Q142"

# Région de France instance-of QIDs
REGION_INSTANCE_QIDS = {
    "Q36784",   # région de France (post-2016)
    "Q202216",  # région historique de France
    "Q3502482", # collectivité territoriale unique
}
# Département de France instance-of QID
DEPT_INSTANCE_QID = "Q6465"

DEPT_TO_REGION = {
    'Ain': 'Auvergne-Rhône-Alpes', 'Aisne': 'Hauts-de-France',
    'Allier': 'Auvergne-Rhône-Alpes', 'Alpes-de-Haute-Provence': "Provence-Alpes-Côte d'Azur",
    'Hautes-Alpes': "Provence-Alpes-Côte d'Azur", 'Alpes-Maritimes': "Provence-Alpes-Côte d'Azur",
    'Ardèche': 'Auvergne-Rhône-Alpes', 'Ardennes': 'Grand Est', 'Ariège': 'Occitanie',
    'Aube': 'Grand Est', 'Aude': 'Occitanie', 'Aveyron': 'Occitanie',
    'Bouches-du-Rhône': "Provence-Alpes-Côte d'Azur", 'Calvados': 'Normandie',
    'Cantal': 'Auvergne-Rhône-Alpes', 'Charente': 'Nouvelle-Aquitaine',
    'Charente-Maritime': 'Nouvelle-Aquitaine', 'Cher': 'Centre-Val de Loire',
    'Corrèze': 'Nouvelle-Aquitaine', 'Corse-du-Sud': 'Corse', 'Haute-Corse': 'Corse',
    "Côte-d'Or": 'Bourgogne-Franche-Comté', "Côtes-d'Armor": 'Bretagne',
    'Creuse': 'Nouvelle-Aquitaine', 'Dordogne': 'Nouvelle-Aquitaine',
    'Doubs': 'Bourgogne-Franche-Comté', 'Drôme': 'Auvergne-Rhône-Alpes',
    'Eure': 'Normandie', 'Eure-et-Loir': 'Centre-Val de Loire', 'Finistère': 'Bretagne',
    'Gard': 'Occitanie', 'Haute-Garonne': 'Occitanie', 'Gers': 'Occitanie',
    'Gironde': 'Nouvelle-Aquitaine', 'Hérault': 'Occitanie', 'Ille-et-Vilaine': 'Bretagne',
    'Indre': 'Centre-Val de Loire', 'Indre-et-Loire': 'Centre-Val de Loire',
    'Isère': 'Auvergne-Rhône-Alpes', 'Jura': 'Bourgogne-Franche-Comté',
    'Landes': 'Nouvelle-Aquitaine', 'Loir-et-Cher': 'Centre-Val de Loire',
    'Loire': 'Auvergne-Rhône-Alpes', 'Haute-Loire': 'Auvergne-Rhône-Alpes',
    'Loire-Atlantique': 'Pays de la Loire', 'Loiret': 'Centre-Val de Loire',
    'Lot': 'Occitanie', 'Lot-et-Garonne': 'Nouvelle-Aquitaine', 'Lozère': 'Occitanie',
    'Maine-et-Loire': 'Pays de la Loire', 'Manche': 'Normandie', 'Marne': 'Grand Est',
    'Haute-Marne': 'Grand Est', 'Mayenne': 'Pays de la Loire',
    'Meurthe-et-Moselle': 'Grand Est', 'Meuse': 'Grand Est', 'Morbihan': 'Bretagne',
    'Moselle': 'Grand Est', 'Nièvre': 'Bourgogne-Franche-Comté', 'Nord': 'Hauts-de-France',
    'Oise': 'Hauts-de-France', 'Orne': 'Normandie', 'Pas-de-Calais': 'Hauts-de-France',
    'Puy-de-Dôme': 'Auvergne-Rhône-Alpes', 'Pyrénées-Atlantiques': 'Nouvelle-Aquitaine',
    'Hautes-Pyrénées': 'Occitanie', 'Pyrénées-Orientales': 'Occitanie',
    'Bas-Rhin': 'Grand Est', 'Haut-Rhin': 'Grand Est', 'Rhin': 'Grand Est',
    'Rhône': 'Auvergne-Rhône-Alpes', 'Haute-Saône': 'Bourgogne-Franche-Comté',
    'Saône-et-Loire': 'Bourgogne-Franche-Comté', 'Sarthe': 'Pays de la Loire',
    'Savoie': 'Auvergne-Rhône-Alpes', 'Haute-Savoie': 'Auvergne-Rhône-Alpes',
    'Paris': 'Île-de-France', 'Seine-Maritime': 'Normandie',
    'Seine-et-Marne': 'Île-de-France', 'Yvelines': 'Île-de-France',
    'Deux-Sèvres': 'Nouvelle-Aquitaine', 'Somme': 'Hauts-de-France',
    'Tarn': 'Occitanie', 'Tarn-et-Garonne': 'Occitanie',
    'Var': "Provence-Alpes-Côte d'Azur", 'Vaucluse': "Provence-Alpes-Côte d'Azur",
    'Vendée': 'Pays de la Loire', 'Vienne': 'Nouvelle-Aquitaine',
    'Haute-Vienne': 'Nouvelle-Aquitaine', 'Vosges': 'Grand Est',
    'Yonne': 'Bourgogne-Franche-Comté', 'Territoire de Belfort': 'Bourgogne-Franche-Comté',
    'Essonne': 'Île-de-France', 'Hauts-de-Seine': 'Île-de-France',
    'Seine-Saint-Denis': 'Île-de-France', 'Val-de-Marne': 'Île-de-France',
    "Val-d'Oise": 'Île-de-France',
    # DOM
    'Guadeloupe': 'Guadeloupe', 'Martinique': 'Martinique', 'Guyane': 'Guyane',
    'La Réunion': 'La Réunion', 'Réunion': 'La Réunion', 'Mayotte': 'Mayotte',
    # Historical names
    'Seine': 'Île-de-France', 'Seine-et-Oise': 'Île-de-France',
    'Seine-Inférieure': 'Normandie', 'Basses-Alpes': "Provence-Alpes-Côte d'Azur",
    'Basses-Pyrénées': 'Nouvelle-Aquitaine', 'Côtes-du-Nord': 'Bretagne',
    'Alsace': 'Grand Est', 'Rhône-et-Loire': 'Auvergne-Rhône-Alpes',
}


# ---------------------------------------------------------------------------
# HTTP helper
# ---------------------------------------------------------------------------

def api_get(params, retries=3):
    params["format"] = "json"
    url = WD_ACTION + "?" + urllib.parse.urlencode(params)
    req = urllib.request.Request(
        url, headers={"User-Agent": "BirthLocationBot/1.0 (politics.json enrichment)"}
    )
    for attempt in range(retries):
        try:
            with urllib.request.urlopen(req, timeout=20) as r:
                return json.loads(r.read())
        except urllib.error.HTTPError as e:
            if e.code == 429:
                wait = int(e.headers.get("Retry-After", 60)) + 5
                print(f"  [429 wait {wait}s]", flush=True)
                time.sleep(wait)
            elif attempt < retries - 1:
                time.sleep(2 * (attempt + 1))
        except Exception:
            if attempt < retries - 1:
                time.sleep(2)
    return None


def load_cache(path):
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return {}


def save_cache(data, path):
    with open(path, "w") as f:
        json.dump(data, f, ensure_ascii=False)


# ---------------------------------------------------------------------------
# Phase 1: P19 per politician
# ---------------------------------------------------------------------------

def fetch_p19_batch(qids):
    resp = api_get({
        "action": "wbgetentities",
        "ids": "|".join(qids),
        "props": "claims",
    })
    if not resp:
        return {}
    result = {}
    for qid, entity in resp.get("entities", {}).items():
        p19 = entity.get("claims", {}).get("P19", [])
        commune_qid = None
        if p19:
            ms = p19[0].get("mainsnak", {})
            if ms.get("snaktype") == "value":
                commune_qid = ms.get("datavalue", {}).get("value", {}).get("id")
        result[qid] = commune_qid
    return result


# ---------------------------------------------------------------------------
# Phase 2: Commune → labels + P131 parents + P17 country
# ---------------------------------------------------------------------------

def fetch_commune_batch(qids):
    resp = api_get({
        "action": "wbgetentities",
        "ids": "|".join(qids),
        "props": "labels|claims",
        "languages": "fr",
    })
    if not resp:
        return {}
    result = {}
    for qid, entity in resp.get("entities", {}).items():
        label = entity.get("labels", {}).get("fr", {}).get("value")
        # P131: located in administrative territorial entity
        p131_qids = [
            c["mainsnak"]["datavalue"]["value"]["id"]
            for c in entity.get("claims", {}).get("P131", [])
            if c.get("mainsnak", {}).get("snaktype") == "value"
        ]
        # P17: country
        p17_qids = [
            c["mainsnak"]["datavalue"]["value"]["id"]
            for c in entity.get("claims", {}).get("P17", [])
            if c.get("mainsnak", {}).get("snaktype") == "value"
        ]
        result[qid] = {
            "label": label,
            "p131": p131_qids,
            "p17": p17_qids[0] if p17_qids else None,
        }
    return result


# ---------------------------------------------------------------------------
# Phase 3: Admin entities → labels + P31 instance-of
# ---------------------------------------------------------------------------

def fetch_admin_batch(qids):
    resp = api_get({
        "action": "wbgetentities",
        "ids": "|".join(qids),
        "props": "labels|claims",
        "languages": "fr",
    })
    if not resp:
        return {}
    result = {}
    for qid, entity in resp.get("entities", {}).items():
        label = entity.get("labels", {}).get("fr", {}).get("value")
        p31_qids = [
            c["mainsnak"]["datavalue"]["value"]["id"]
            for c in entity.get("claims", {}).get("P31", [])
            if c.get("mainsnak", {}).get("snaktype") == "value"
        ]
        # Also fetch P131 (parent admin entity) so we can walk up the chain
        p131_qids = [
            c["mainsnak"]["datavalue"]["value"]["id"]
            for c in entity.get("claims", {}).get("P131", [])
            if c.get("mainsnak", {}).get("snaktype") == "value"
        ]
        result[qid] = {"label": label, "p31": p31_qids, "p131": p131_qids}
    return result


# ---------------------------------------------------------------------------
# Region resolution
# ---------------------------------------------------------------------------

def _check_entity(entity_qid, admin_cache):
    """Return region string if this entity IS a région or département, else None."""
    info = admin_cache.get(entity_qid, {})
    p31  = set(info.get("p31", []))
    label = info.get("label", "")
    if p31 & REGION_INSTANCE_QIDS:
        return label
    if DEPT_INSTANCE_QID in p31 and label in DEPT_TO_REGION:
        return DEPT_TO_REGION[label]
    if label in DEPT_TO_REGION:
        return DEPT_TO_REGION[label]
    return None


def resolve_region(commune_qid, commune_cache, admin_cache):
    """Return (region_string, is_france) for a commune QID. Walks up to 3 P131 levels."""
    comm = commune_cache.get(commune_qid)
    if not comm:
        return None, None

    country = comm.get("p17")
    is_france = (country == FRANCE_QID)

    if not is_france:
        country_info = admin_cache.get(country, {})
        return country_info.get("label"), False

    # BFS walk through P131 chain (commune → arr. → dept → region)
    visited = set()
    frontier = list(comm.get("p131", []))

    for _ in range(4):  # max 4 hops
        next_frontier = []
        for qid in frontier:
            if qid in visited:
                continue
            visited.add(qid)
            region = _check_entity(qid, admin_cache)
            if region:
                return region, True
            # Go one level up
            parent_info = admin_cache.get(qid, {})
            next_frontier.extend(parent_info.get("p131", []))
        frontier = next_frontier
        if not frontier:
            break

    # Fallback: commune label itself is a département name (e.g. Paris)
    comm_label = comm.get("label", "")
    if comm_label in DEPT_TO_REGION:
        return DEPT_TO_REGION[comm_label], True

    return None, True  # French but unresolved


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    with open(POLITICS) as f:
        data = json.load(f)
    membres = data["membres"]
    total   = len(membres)

    qid_cache = load_cache(QID_CACHE)

    # ---- Phase 1: P19 ----
    print("Phase 1: Fetching P19 (place of birth)…", flush=True)
    p19_cache = load_cache(P19_CACHE)
    all_qids  = [v for v in qid_cache.values() if v]
    need_p19  = [q for q in all_qids if q not in p19_cache]
    print(f"  Cached: {len(p19_cache)}, need: {len(need_p19)}", flush=True)

    for i in range(0, len(need_p19), BATCH):
        batch  = need_p19[i:i + BATCH]
        result = fetch_p19_batch(batch)
        p19_cache.update(result)
        save_cache(p19_cache, P19_CACHE)
        found = sum(1 for v in p19_cache.values() if v)
        print(f"  [{min(i+BATCH, len(need_p19))}/{len(need_p19)}] communes found: {found}", flush=True)
        time.sleep(1.5)

    commune_qids = {v for v in p19_cache.values() if v}
    print(f"  Unique communes: {len(commune_qids)}", flush=True)

    # ---- Phase 2: Commune data ----
    print("\nPhase 2: Fetching commune data (labels + P131 + P17)…", flush=True)
    commune_cache = load_cache(COMMUNE_CACHE)
    need_comm     = [q for q in commune_qids if q not in commune_cache]
    print(f"  Cached: {len(commune_cache)}, need: {len(need_comm)}", flush=True)

    for i in range(0, len(need_comm), BATCH):
        batch  = need_comm[i:i + BATCH]
        result = fetch_commune_batch(batch)
        commune_cache.update(result)
        save_cache(commune_cache, COMMUNE_CACHE)
        print(f"  [{min(i+BATCH, len(need_comm))}/{len(need_comm)}] commune batches done", flush=True)
        time.sleep(1.0)

    # ---- Phase 3: Admin parent data ----
    print("\nPhase 3: Fetching admin parent labels + P31…", flush=True)
    admin_cache = load_cache(ADMIN_CACHE)

    # Collect: all P131 parents + all P17 countries
    parent_qids = set()
    for comm in commune_cache.values():
        parent_qids.update(comm.get("p131", []))
        if comm.get("p17"):
            parent_qids.add(comm["p17"])

    need_admin = [q for q in parent_qids if q not in admin_cache]
    print(f"  Unique admin entities: {len(parent_qids)}, need: {len(need_admin)}", flush=True)

    for i in range(0, len(need_admin), BATCH):
        batch  = need_admin[i:i + BATCH]
        result = fetch_admin_batch(batch)
        admin_cache.update(result)
        save_cache(admin_cache, ADMIN_CACHE)
        print(f"  [{min(i+BATCH, len(need_admin))}/{len(need_admin)}] admin batches done", flush=True)
        time.sleep(1.0)

    # ---- Phase 4: Write results ----
    print("\nPhase 4: Writing politics.json…", flush=True)
    found_france = 0
    found_abroad = 0
    not_found    = 0

    for m in membres:
        name_key     = f"{m['prenom']} {m['nom']}"
        pol_qid      = qid_cache.get(name_key)
        commune_qid  = p19_cache.get(pol_qid) if pol_qid else None

        if not commune_qid:
            m["originRegion"] = None
            not_found += 1
            continue

        region, is_france = resolve_region(commune_qid, commune_cache, admin_cache)
        m["originRegion"] = region

        if region:
            if is_france:
                found_france += 1
            else:
                found_abroad += 1
        else:
            not_found += 1

    with open(POLITICS, "w") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total_found = sum(1 for m in membres if m.get("originRegion"))
    print(f"\nDone!")
    print(f"  France (region):  {found_france}")
    print(f"  Abroad (country): {found_abroad}")
    print(f"  Not resolved:     {not_found}")
    print(f"  originRegion set: {total_found}/{total}", flush=True)


if __name__ == "__main__":
    main()
